import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.tsx";

// This is the entry point of the application
// It renders the App component inside the root element
// The App component is wrapped in a StrictMode element
// to enable additional checks and warnings for the application
// All this code is generated by vite
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
